### ISSUE TITLE
Fix theme version

### ISSUE THREAD

**Issue by lcnzg** [go-br/gopher.pro.br#1]
The deployed site has a problem with the home and post pages. This issue is related to newer versions of hugo in conjunction with the old theme.

A common practice is to use the theme repository as a submodule, which makes it easy to update themes.

**Comment by crgimenes** [comment]
Maybe it's a good time to change the theme.

I was thinking of rewriting theme from scratch for fast loading, the site statistics show a lot of people accessing 3g and any bandwidth savings is welcome.
